version: "3.9"
services:
  db:
    image: postgres:16
    container_name: poc_db
    restart: always
    environment:
      POSTGRES_USER: poc_user
      POSTGRES_PASSWORD: poc_pass
      POSTGRES_DB: poc_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: